### ISSUE TITLE
segmentation loss

### ISSUE THREAD

**Issue by poorneshwaran** [NifTK/NiftyNetModelZoo#15]
I have used your code from past week. It works good, recently i got error like "segmentation loss: Could not import object"dice" from "dense_vnet_abdominal_ct.dice_hinge". Module not found dense_vnet_abdominal_ct

python version =3.6
conda tensorflow 1.14 these are the package I'm using

**Comment by wyli** [comment]
Hi @poorneshwaran could you upload the exact error message?
the previous version of  "dense_vnet_abdominal_ct.dice_hinge" is not compatible with tensorflow 1.14, you can get the latest version by `python net_download.py -r dense_vnet_abdominal_ct_model_zoo`

**Comment by poorneshwaran** [comment]
Sorry I wrongly post the issue in NifTK/NiftyNetModelZoo instead NifTK/NiftyNet .
