### ISSUE TITLE
Reorganise entries and use LFS for zipped files

### ISSUE THREAD

**Issue by fepegar** [NifTK/NiftyNetModelZoo#5]
- [x] Each model zoo entry should have its own directory
- [x] The models weights can be in the corresponding directory and stored with [Git LFS](https://git-lfs.github.com/)

**Comment by fepegar** [comment]
@dzhoshkun, can you please give @wyli and me rights for this?

**Comment by dzhoshkun** [comment]
I've made you both admins on this repo now. You should've received a notification/invitation by email.

**Comment by wyli** [comment]
implemented at https://github.com/NifTK/NiftyNetModelZoo/tree/5-reorganising-with-lfs
