### ISSUE TITLE
contributing guide

### ISSUE THREAD

**Issue by wyli** [NifTK/NiftyNetModelZoo#8]
A guide on how to add new entries to the zoo should be presented here https://niftynet.readthedocs.io/en/dev/

**Comment by tvercaut** [comment]
Looks good. I am reopening this as it would also be good to point to the documentation (https://niftynet.readthedocs.io/en/dev/contributing.html#submitting-model-zoo-entries) from here https://niftynet.readthedocs.io/en/dev/extending_net.html#share-the-network-and-trained-weights rather than say 
> Please consider submitting the design to our model zoo (contact niftynet-team@googlegroups.com if interested).
